### ISSUE TITLE
モックデータを使おうとするとエラーが出ます

### ISSUE THREAD

**Issue by Axafy5479** [ut-code/syllabus-next#34]
新しくページを作り以下のコードを書いたのですがエラーが出ます。

``` typescript
import { fetchClasses } from "@/app/utils/user"

const Temp:React.FC = ()=>{
    var classes = fetchClasses();
    console.log(classes);
    return <div></div>;
}

export default Temp;
```
(mainからの変更はこのファイルの追加だけです。)

内容は次のようになっています。
![image](https://github.com/user-attachments/assets/83df9984-7a2d-45bf-a8f3-b13a7bb11f24)

恐らくuser.tsが"use client"だからじゃないか、と思っています。
サーバーコンポーネントからクライアントコンポーネントは呼べない、といったルールがあるのでしょうか?

**Comment by Yokomi422** [comment]
サーバコンポーネントは、クライアントコンポーネントのuser.ts(users.tsにuse clientと書いてあるから)は呼べないですね。サーバコンポーネントはサーバの方でrenderingされるので、クライアント(ブラウザなど)で定義されるuseStateとかlocalStorageを持つクライアントコンポーネントを中に持つことはできないです。user.tsにuse clientと書いてあるので、この中にある関数を使いたいコンポーネントの先頭にuse clientと書けば動くはずです。

**Comment by Yokomi422** [comment]
`Sample/Temp/page.tsx`の先頭にuse clientを書けば動くはずです。

**Comment by Yokomi422** [comment]
user.tsはlocalStorageというサーバでは値を決定できないデータを使うので、use clientになる必要があります。

**Comment by Axafy5479** [comment]
分かりました!
ありがとうございます
